# Generated by Django 5.2.7 on 2026-03-11 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Tell us about yourself", max_length=500
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Your location", max_length=100
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Your website or social media"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Your phone number", max_length=20
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="Your birth date", null=True
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a profile picture",
                        null=True,
                        upload_to="profile_pics/",
                    ),
                ),
                (
                    "cover_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a cover picture",
                        null=True,
                        upload_to="cover_pics/",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether this user is verified"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
