# Generated by Django 5.2.7 on 2026-05-15 00:35
#
# Modified to use RunSQL with IF NOT EXISTS so the migration is idempotent
# and safe to run against databases that already have the user_id column.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_created_at_chatroom_is_group_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward: add user_id column only if it doesn't already exist
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'chat_message'
                          AND column_name = 'user_id'
                    ) THEN
                        ALTER TABLE chat_message
                        ADD COLUMN user_id integer NOT NULL
                        REFERENCES auth_user(id) ON DELETE CASCADE;
                    END IF;
                END $$;
            """,
            # Reverse: drop the column
            reverse_sql="""
                ALTER TABLE chat_message DROP COLUMN IF EXISTS user_id;
            """,
            state_operations=[
                migrations.AddField(
                    model_name='message',
                    name='user',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
